# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
from datetime import date
import sys
import sphinx_bootstrap_theme
import frites
from sphinx_gallery.sorting import ExplicitOrder
# sys.path.insert(0, os.path.abspath('.'))
sys.path.insert(0, os.path.abspath('sphinxext'))
bibtex_bibfiles = ['refs.bib']


# -- Project information -----------------------------------------------------

project = 'frites'
td = date.today()
copyright = 'Last updated on %s' % td.isoformat()
author = 'Etienne Combrisson'

# The short X.Y version
version = frites.__version__
# The full version, including alpha/beta/rc tags
release = frites.__version__


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
    'sphinx.ext.autosummary',
    'sphinx_gallery.gen_gallery',
    'sphinxcontrib.bibtex',
    "sphinx.ext.extlinks",
    'numpydoc'
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

autosummary_generate = True
autodoc_member_order = 'groupwise'
autodoc_default_flags = ['members', 'inherited-members', 'no-undoc-members']

extlinks = {
    "issue": ("https://github.com/brainets/frites/issues/%s", "IS"),
    "pull": ("https://github.com/brainets/frites/pull/%s", "PR"),
    "commit": ("https://github.com/brainets/frites/commit/%s", "CM"),
}

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = 'alabaster'
html_theme_path = sphinx_bootstrap_theme.get_html_theme_path()
html_theme = 'bootstrap'
html_theme_options = {
    'bootstrap_version': "3",
    'navbar_site_name': "Site",
    'navbar_sidebarrel': False,
    'navbar_pagenav': True,
    'navbar_pagenav_name': "Page",
    'globaltoc_depth': -1,
    'globaltoc_includehidden': "true",
    'source_link_position': "nav",
    'navbar_class': "navbar",
    'bootswatch_theme': "readable",
    'navbar_fixed_top': True,
    'navbar_links': [
        ("Overview", "overview"),
        ("Install", "install"),
        ("Community", "community"),
        ("API", "api"),
        ("Examples", "auto_examples/index"),
    ],
}

sphinx_gallery_conf = {
    # path to your examples scripts
    'examples_dirs': '../../examples',
    'sphinx_gallery': None,
    'reference_url': {
        'frites': None,
        'matplotlib': 'https://matplotlib.org',
        'numpy': 'http://docs.scipy.org/doc/numpy',
        'scipy': 'http://docs.scipy.org/doc/scipy/reference',
        'pandas': 'https://pandas.pydata.org/pandas-docs/stable',
        'statsmodels': 'http://www.statsmodels.org/stable/',
    },
    'gallery_dirs': 'auto_examples',
    'backreferences_dir': 'generated',
    'filename_pattern': '/plot_|sim_',
    'default_thumb_file': 'source/_static/frites.png',
    'subsection_order': ExplicitOrder([
        '../../examples/tutorials',
        '../../examples/dataset',
        '../../examples/mi',
        '../../examples/estimators',
        '../../examples/conn',
        '../../examples/armodel',
        '../../examples/utils',
        '../../examples/statistics',
        '../../examples/simulations',
        '../../examples/xarray'
        ]),
    # 'thumbnail_size': (100, 100),
}

numpydoc_show_class_members = False
# numpydoc_class_members_toctree = False
# numpydoc_use_blockquotes = False

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'fritesdoc'

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = '_static/frites_128x128.png'

# The name of an image file (relative to this directory) to use as a favicon of
# the docs.  This file should be a Windows icon file (.ico) being 16x16 or
# 32x32 pixels large.
html_favicon = '_static/favicon.ico'

html_show_sourcelink = False

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'frites.tex', 'frites Documentation',
     'Etienne Combrisson', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'frites', 'frites Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'frites', 'frites Documentation',
     author, 'frites', 'One line description of project.',
     'Miscellaneous'),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']


# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'https://docs.python.org/': None}

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


def setup(app):  # noqa
    app.add_stylesheet("frites_style.css")
