name: "Code quality"

on:
  push:
    branches: [ master ]

jobs:

  flake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4.0.0

      - name: Set up Python 🔧
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies 🔧
        run: |
          python -m pip install --upgrade pip
          pip install -e .['flake']

      - name: Test code quality 🔧
        run: |
          flake8
